name: Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Tests for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        working-directory: .
        run: cargo test --all-features --verbose

      - name: Build Binaries
        working-directory: .
        run: cargo build --release --verbose
